language: bash

before_script:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh && bash ./travis-tool.sh bootstrap
  - chmod +x bbb

script:
  - cd test && bash vendor/roundup.sh
